services:
    ghost:
        image: ghost:latest
        container_name: ghost-rtlx
        hostname: ghost-RTLx
        volumes:
        - ./config.production.json:/var/lib/ghost/config.production.json:z
        - ./ghost:/var/lib/ghost/content
        environment:
            NODE_ENV: production
        restart: unless-stopped
        networks:
        - ghost
        - frontend
        labels:
        - traefik.enable=true
        - traefik.docker.network=frontend
        - traefik.http.routers.ghost-rtlx.tls.certresolver=myresolver
        - traefik.http.routers.ghost-rtlx.rule=Host(`$DOMAIN`) 
        depends_on:
        - mysql

    mysql:
        image: mysql:8
        container_name: ghost-mysql
        hostname: ghost-mysql
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_USER: user
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: ghost
        restart: unless-stopped
        networks:
        - ghost



networks:
    ghost:
        internal: true
    frontend:
        external: true
